import { Lead, LeadStatus, LeadTier, SavedSearch } from './types';

export const PROBLEM_FILTER_OPTIONS = [
  'No website',
  'Low rating',
  'No social presence',
  'Outdated website',
  'No booking system',
];

export const CONTACT_PREFERENCE_OPTIONS = ['Any', 'Email', 'Phone', 'LinkedIn'] as const;

export const STATUS_OPTIONS: LeadStatus[] = ['New', 'Pending', 'Contacted', 'Won', 'Lost', 'Archived'];

export const TIER_OPTIONS: Array<LeadTier | 'All'> = ['All', 'Tier 1', 'Tier 2', 'Tier 3'];

export const TIER_META: Record<LeadTier, { title: string; subtitle: string }> = {
  'Tier 1': {
    title: 'Most Valuable Leads (Tier 1)',
    subtitle: 'High priority opportunities',
  },
  'Tier 2': {
    title: 'Probable Leads (Tier 2)',
    subtitle: 'Strong opportunities to nurture',
  },
  'Tier 3': {
    title: 'Raw Leads (Tier 3)',
    subtitle: 'Early-stage opportunities',
  },
};

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    businessName: 'Summit Coffee Roasters',
    location: 'Seattle, WA',
    category: 'Cafe',
    problems: ['No website', 'Low rating (3.2★)'],
    explanation: 'Active business with regular customers but no online ordering and weak digital conversion paths.',
    tier: 'Tier 1',
    score: 96,
    status: 'New',
    contactChannels: ['Email', 'Phone'],
  },
  {
    id: 'lead-2',
    businessName: 'Precision Auto Repair',
    location: 'Austin, TX',
    category: 'Auto Service',
    problems: ['No social presence', 'No booking system'],
    explanation: 'Established shop with strong local reputation but limited digital lead intake and appointment friction.',
    tier: 'Tier 2',
    score: 84,
    status: 'Pending',
    contactChannels: ['Phone'],
  },
  {
    id: 'lead-3',
    businessName: 'Bloom Floral Design',
    location: 'Portland, OR',
    category: 'Florist',
    problems: ['Outdated website', 'No online ordering'],
    explanation: 'High demand florist still running an old site without a modern ordering workflow.',
    tier: 'Tier 1',
    score: 92,
    status: 'Contacted',
    contactChannels: ['Email', 'Instagram'],
  },
  {
    id: 'lead-4',
    businessName: 'Harbor Family Dentistry',
    location: 'San Diego, CA',
    category: 'Dental Clinic',
    problems: ['No booking system'],
    explanation: 'Patient reviews cite booking friction and long callback times; clear conversion improvement opportunity.',
    tier: 'Tier 2',
    score: 79,
    status: 'New',
    contactChannels: ['Email', 'LinkedIn'],
  },
  {
    id: 'lead-5',
    businessName: 'Trailhead Roofing',
    location: 'Denver, CO',
    category: 'Roofing',
    problems: ['No website'],
    explanation: 'Solid offline referrals but weak lead capture online, especially for storm-season demand spikes.',
    tier: 'Tier 3',
    score: 68,
    status: 'Pending',
    contactChannels: ['Phone', 'LinkedIn'],
  },
  {
    id: 'lead-6',
    businessName: 'Bluebird Pediatrics',
    location: 'Phoenix, AZ',
    category: 'Pediatrics',
    problems: ['No social presence', 'No online forms'],
    explanation: 'Strong local trust but digital onboarding and communication flow are outdated for new patient intake.',
    tier: 'Tier 1',
    score: 94,
    status: 'Won',
    contactChannels: ['Email'],
  },
  {
    id: 'lead-7',
    businessName: 'Maple Street Physio',
    location: 'Nashville, TN',
    category: 'Physical Therapy',
    problems: ['Outdated website', 'No booking system'],
    explanation: 'High intent traffic but poor conversion from website visits to appointment confirmations.',
    tier: 'Tier 2',
    score: 82,
    status: 'Contacted',
    contactChannels: ['Phone', 'Email'],
  },
  {
    id: 'lead-8',
    businessName: 'Brightline Legal Group',
    location: 'Chicago, IL',
    category: 'Legal Services',
    problems: ['Low rating (3.5★)', 'No social presence'],
    explanation: 'Good service mix, but inconsistent review profile and low trust signals are reducing inbound conversions.',
    tier: 'Tier 1',
    score: 90,
    status: 'Pending',
    contactChannels: ['LinkedIn', 'Email'],
  },
  {
    id: 'lead-9',
    businessName: 'Stonebridge Landscapes',
    location: 'Raleigh, NC',
    category: 'Landscaping',
    problems: ['No website', 'No booking system'],
    explanation: 'Seasonal demand is strong but opportunities are missed due to manual quoting and scheduling.',
    tier: 'Tier 3',
    score: 62,
    status: 'New',
    contactChannels: ['Phone'],
  },
  {
    id: 'lead-10',
    businessName: 'Northwind Home Cleaning',
    location: 'Minneapolis, MN',
    category: 'Cleaning Services',
    problems: ['No social presence'],
    explanation: 'Consistent neighborhood demand with no active social proof strategy or recurring campaign structure.',
    tier: 'Tier 2',
    score: 77,
    status: 'Lost',
    contactChannels: ['Email', 'Phone'],
  },
  {
    id: 'lead-11',
    businessName: 'Evergreen Eye Care',
    location: 'Boise, ID',
    category: 'Optometry',
    problems: ['Outdated website'],
    explanation: 'Trusted practice with strong retention but outdated web experience limits new-patient acquisition.',
    tier: 'Tier 1',
    score: 95,
    status: 'Archived',
    contactChannels: ['Email'],
  },
  {
    id: 'lead-12',
    businessName: 'Ironclad Fitness Studio',
    location: 'Miami, FL',
    category: 'Fitness',
    problems: ['Low rating (3.6★)', 'No booking system'],
    explanation: 'Class demand exists but signup friction and inconsistent member communication hurt conversion rates.',
    tier: 'Tier 3',
    score: 64,
    status: 'Pending',
    contactChannels: ['Instagram', 'Phone'],
  },
];

export const INITIAL_SAVED_SEARCHES: SavedSearch[] = [
  {
    id: 'saved-1',
    name: 'Seattle Cafes',
    config: {
      location: 'Seattle, WA',
      category: 'Cafe',
      problemFilters: ['No website', 'Low rating'],
      contactPreference: 'Email',
    },
  },
  {
    id: 'saved-2',
    name: 'Dental Prospects',
    config: {
      location: 'California',
      category: 'Dental Clinic',
      problemFilters: ['No booking system'],
      contactPreference: 'Phone',
    },
  },
];
